#!/usr/bin/env bash
# Configure a Sikarugir (Wineskin) wrapper for DXVK + hardware-aware memory tuning.
#
# Usage:
#   ./scripts/configure_sikarugir_wrapper.sh "/path/to/YourWrapper.app"
#   ./scripts/configure_sikarugir_wrapper.sh   # defaults to ~/Applications/Sikarugir/Stream.app
#
# What it does:
#   - Enables DXVK in the wrapper Info.plist (Intel Macs: DXVK, not D3DMetal)
#   - Points the wrapper at steam.exe (if installed in the prefix)
#   - Installs a StartupScript that detects RAM/VRAM and writes dxvk.conf each launch
set -euo pipefail

WRAPPER="${1:-$HOME/Applications/Sikarugir/Stream.app}"
PLIST="${WRAPPER}/Contents/Info.plist"
PREFIX="${WRAPPER}/Contents/SharedSupport/prefix"
STARTUP="${WRAPPER}/Contents/Resources/Scripts/StartupScript"
STEAM_WIN='C:\Program Files (x86)\Steam\steam.exe'
STEAM_UNIX="${PREFIX}/drive_c/Program Files (x86)/Steam/steam.exe"

die() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

[[ -d "${WRAPPER}" ]] || die "Wrapper not found: ${WRAPPER}"
[[ -f "${PLIST}" ]] || die "Info.plist missing in wrapper"
[[ -d "${PREFIX}" ]] || die "Wine prefix missing in wrapper"

log() {
  printf '==> %s\n' "$1"
}

detect_ram_mb() {
  local bytes
  bytes="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
  printf '%s\n' "$(( bytes / 1048576 ))"
}

detect_vram_mb() {
  local line num unit
  line="$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/VRAM/ {print $2; exit}')"
  [[ -n "${line}" ]] || { printf '1536\n'; return; }
  num="$(printf '%s' "${line}" | grep -oE '[0-9]+' | head -1)"
  unit="$(printf '%s' "${line}" | grep -oiE '[a-z]+' | head -1)"
  [[ -n "${num}" ]] || { printf '1536\n'; return; }
  case "${unit}" in
    [Gg][Bb]) printf '%s\n' "$(( num * 1024 ))" ;;
    *)        printf '%s\n' "${num}" ;;
  esac
}

log "Configuring ${WRAPPER}"

# Enable DXVK (disable Apple-Silicon-only backends).
/usr/libexec/PlistBuddy -c 'Set :DXVK 1' "${PLIST}"
/usr/libexec/PlistBuddy -c 'Set :D3DMETAL 0' "${PLIST}"
/usr/libexec/PlistBuddy -c 'Set :DXMT 0' "${PLIST}"
/usr/libexec/PlistBuddy -c 'Set :D9VK 0' "${PLIST}"
log "Enabled DXVK in Info.plist"

if [[ -f "${STEAM_UNIX}" ]]; then
  /usr/libexec/PlistBuddy -c 'Set :Program\ Name\ and\ Path C:\\Program\ Files\ \(x86\)\\Steam\\steam.exe' "${PLIST}"
  log "Set main program to ${STEAM_WIN}"
else
  log "Steam not found in prefix yet — skipping Program Name and Path (install Steam first, then re-run)"
fi

mkdir -p "$(dirname "${STARTUP}")"
cat > "${STARTUP}" <<'SCRIPT'
#!/bin/sh
# Auto-generated by macos-wine-steam-intel/scripts/configure_sikarugir_wrapper.sh
# Detects this Mac's RAM/VRAM and exports DXVK_CONFIG_FILE before Wine starts.
cd "$(dirname "$0")/../../" || exit 0
CONTENTSFOLD="$PWD"
PREFIX="${CONTENTSFOLD}/SharedSupport/prefix"
CONF="${PREFIX}/dxvk.conf"

ram_mb=$(($(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1048576))
[ "${ram_mb}" -gt 0 ] || ram_mb=4096

vram_line=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/VRAM/ {print $2; exit}')
vram_mb=1536
if [ -n "${vram_line}" ]; then
  vnum=$(printf '%s' "${vram_line}" | grep -oE '[0-9]+' | head -1)
  vunit=$(printf '%s' "${vram_line}" | grep -oiE '[a-z]+' | head -1)
  case "${vunit}" in
    [Gg][Bb]|[gG][bB]) vram_mb=$((vnum * 1024)) ;;
    *) [ -n "${vnum}" ] && vram_mb="${vnum}" ;;
  esac
fi

shared_mb=$((ram_mb / 4))
[ "${shared_mb}" -lt 1024 ] && shared_mb=1024
[ "${shared_mb}" -gt 8192 ] && shared_mb=8192

cat > "${CONF}" <<EOF
# Auto-generated at wrapper launch from detected hardware.
# ${ram_mb} MB RAM, ${vram_mb} MB VRAM
dxgi.maxDeviceMemory = ${vram_mb}
dxgi.maxSharedMemory = ${shared_mb}
d3d9.maxAvailableMemory = ${vram_mb}
EOF

export DXVK_CONFIG_FILE="${CONF}"
SCRIPT
chmod +x "${STARTUP}"
log "Installed memory-aware StartupScript"

# Write an initial dxvk.conf now (StartupScript refreshes it on each launch).
ram_mb="$(detect_ram_mb)"
vram_mb="$(detect_vram_mb)"
shared_mb=$(( ram_mb / 4 ))
(( shared_mb < 1024 )) && shared_mb=1024
(( shared_mb > 8192 )) && shared_mb=8192

cat > "${PREFIX}/dxvk.conf" <<EOF
# Auto-generated by configure_sikarugir_wrapper.sh
# Detected: ${ram_mb} MB RAM, ${vram_mb} MB VRAM
dxgi.maxDeviceMemory = ${vram_mb}
dxgi.maxSharedMemory = ${shared_mb}
d3d9.maxAvailableMemory = ${vram_mb}
EOF
log "Wrote ${PREFIX}/dxvk.conf (${ram_mb} MB RAM, ${vram_mb} MB VRAM)"

printf '\nDone. Launch %s from Finder.\n' "${WRAPPER}"
printf 'DXVK is enabled; games will use your GPU with memory tuned to this Mac.\n'
